services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscreen
    restart: unless-stopped
    environment:
      - DEMO=false
      - DEBUG=false
      - SECRET_KEY=ANY_SECRET_KEY_HERE
      - PORT=5000
      - PORT_HTTP_EXTERNAL_STORAGE=5001
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
      - 5001:5001
