name: Common Docker Build

on: [workflow_call]

jobs:
  build-and-push-common:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.build_tags }}
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7

      - name: Create and push manifest
        uses: docker/metadata-action@v3
        with:
          images: jierka/obscreen
          tags: ${{ inputs.manifest_tags }}
          flavor: ${{ inputs.flavor }}
