name: Trigger build for PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches-ignore:
      - master
      - develop
      - nightly

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build-pr')

    steps:
    - name: Trigger PR build
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GA_TOKEN }}
        event-type: build-pr
        client-payload: '{"pr_number": ${{ github.event.pull_request.number }}}'
